trigger:
- master

pool:
  vmImage: ubuntu-latest
variables:
  CARBON_VERSION: '1.22.0'

steps:
- task: GoTool@0
  inputs:
    version: '1.13'
- script: |
    go version
    go get -v -t -d ./...
    if [ -f Gopkg.toml ]; then
        curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
        dep ensure
    fi
  displayName: 'Get dependencies'
- task: ComponentGovernanceComponentDetection@0
  inputs:
    scanType: 'Register'
    verbosity: 'Verbose'
    alertWarningLevel: 'High'
- script: |
    mkdir $HOME/carbon
    pushd $HOME/carbon
    wget https://csspeechstorage.blob.core.windows.net/drop/$(CARBON_VERSION)/SpeechSDK-Linux-$(CARBON_VERSION).tar.gz
    tar xzf SpeechSDK-Linux-$(CARBON_VERSION).tar.gz
    rm SpeechSDK-Linux-$(CARBON_VERSION).tar.gz
    ln -s SpeechSDK-Linux-$(CARBON_VERSION) current
    popd
  displayName: 'Get Speech SDK'
- script: |
    sudo apt-get update
    sudo apt-get install libasound2
    sudo apt-get install -y libgstreamer1.0-0 gstreamer1.0-plugins-good
    dpkg -l | grep gstreamer
  displayName: 'Get Speech SDK dependencies'
- script: |
    export CGO_CFLAGS="-I$HOME/carbon/current/include/c_api"
    export CGO_LDFLAGS="-L$HOME/carbon/current/lib/x64 -lMicrosoft.CognitiveServices.Speech.core"
    export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$HOME/carbon/current/lib/x64"
    go build -v ./...
  displayName: 'Build'